---
title: "Quiz 2"
author: "Amanda Mae Woodward"
date: "11/4/2020"
output: html_document
---
This quiz is meant to help you synthesize materials we've covered in class. If you'd prefer to use other functions, that's okay too. 

You ARE allowed to work with your peers, but you should each submit your own copy.

 You should see the following variables: 
subj- subject number
condition- experimental or control
stroop- an accuracy score for the stroop task (30 trials)
nback- an accuracy score for the n back task (recalling a number/object a given number of trials back;50 trials)
ravens- score on raven's progressive matrices (25 trials)

People are assigned to either complete a cognitive training task (to improve memory) or to have no training. We have  

Upload the psych259-Quiz2.csv file.

1. Take a summary of the data
2. What kind of data do you have (wide or long?). How do you know?
3. Run correlations between each variable type at T1 and T2
4.Run a t.test to determine if participants' post test ravens scores differed by condition
5. Create a dataset containing participants' nback scores in long format. 
6. Create a linear model (regression) predicting all nback scores from condition.  

The above does not account for the repeated measurement. In the next  problem, we'll run a mixed model predicting nback scores from condition.
7. Create a mixed model that predicts nback scores from condition and include a random intercept for subject.  
8. Run the same model in #7, but use ravens as the outcome variable. 
9. Run the same model in #8, but use stroop as the outcome variable.

While 7-10 ask you to think through how to program multilevel/mixed models, they don't ask you to think about how to interpret them or what the output means. As a **challenge** interpret your output for each model in this document. If you're looking for even **more of a challenge**, consider whether the above models are the best way to answer "does cognitive training actually improve cognitive abilities?" If you think there are better models, please write them below.  